config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :players do
    resources :comments
  end
  resources :authors
  resources :skills
  resources :teams
  resources :leagues
  resources :positions


  
  root "players#index"
end

app/models/league.rb
class League < ActiveRecord::Base
    has_many :players
    has_many :teams
    validates :name, presence: true
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController

  def index
    @leagues = League.all
  end

  def show 
    @league = League.find(params[:id])
     @players = @league.players.order(created_at: :desc)
  end

  def new 
    @league = League.new
  end

  def create
    @league = League.new(league_params)

    if @league.save
      flash[:notice] = "Thanks for adding this league!"
      redirect_to league_path(@league)
    else
      flash.now[:error] = "Something went wrong, please try again!"
      render :new
    end
  end

  def edit 
    @league = League.find(params[:id])
  end

  def update
    @league = League.find(params[:id])

    if @league.update(league_params)
      redirect_to league_path(@league), notice: "League was successfully updated!"
    else
      flash.now[:error] = "An error occurred when updating this league"
      render :edit
    end
  end

  def destroy
    @league = League.find(params[:id])
    @league.destroy

    redirect_to leagues_path, notice: "League was successfully deleted"
  end

  private

  def league_params
   params.require(:league).permit(:name)
 end

end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/leagues/_form.html.erb
<%= form_for @league do |f| %>

  <% if @league.errors.any? %>
    <% @league.errors.full_messages.each do |message| %>
      <p><%= message %></p>
    <% end %>
  <% end %>

  <p>
    <%= f.label :league_name %><br>
    <%= f.text_field :name %>
  </p>


  <%= f.submit %>
<% end %>

app/views/leagues/edit.html.erb
<h1>Edit League</h1>

<%= link_to "Back to All Leagues", league_path %>

<%= render 'form' %>

app/views/leagues/index.html.erb
<h1>All Leagues</h1>
<h2>
<table>
  <tr>
    <th>League</th>
  </tr>
  <tbody>
    <% @leagues.each do |league| %>
      <tr>
        <td><%= link_to(league.name, league_path(league)) %></td>
        <td>&nbsp 
        </td>
        <td>&nbsp 
        </td>
        <td>&nbsp 
        </td>
        <td>&nbsp 
        </td>
        <td>&nbsp 
        </td>
        <td>&nbsp 
        </td>
        <td>&nbsp 
        </td>
        <td><%= link_to "edit", edit_league_path(league) %></td>
        <td>&nbsp 
        </td>
        <td>&nbsp 
        </td>
        <td><%= link_to "delete", league_path(league), method: :delete, data: {confirm: "Really want to delete this league?"}%></td>
      </tr>
    <% end %>
  </tbody>
</table>
</h2>

<h4><%= link_to "Add a New League", new_league_path %></h4>

<br />
<br />

app/views/leagues/new.html.erb
<h1>Add New Player</h1>


<%= link_to "Back to All Leagues", leagues_path %>
<%= link_to "Back to All Players", players_path %>

<%= render 'form' %>

app/views/leagues/show.html.erb
<%= link_to "Back to All Leagues", leagues_path %>

<p>
  <strong>League:</strong> <%= @league.name %>
</p>

<h3>Players</h3>

<% @players.each do |player| %>
      <tr>
        
        <td><%= image_tag player.photo.url(:small) %></td>
        <strong><td><%= link_to(player.first_name, player_path(player)) %></td>
        <td><%= link_to(player.last_name, player_path(player)) %></td>
        <td>&nbsp 
        </td>
        <td>&nbsp 
        </td>
        <td>&nbsp 
        </td>
        <td><%= link_to(player.team.name, team_path(player.team)) %></td>
        </strong><br><br>
        <% end %>

<br />
<td><%= link_to "edit", edit_league_path(@league) %></td>