config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :players do
    resources :comments
  end
  resources :authors
  resources :skills
  resources :teams
  resources :leagues
  resources :positions


  
  root "players#index"
end

app/models/position.rb
class Position < ActiveRecord::Base
  has_many :players
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
    def index
    @positions = Position.all
  end

  def show 
    @position = Position.find(params[:id])
     @players = @position.players.order(created_at: :desc)
  end

  def new 
    @position = Position.new
  end

  def create
    @position = Position.new(position_params)

    if @position.save
      flash[:notice] = "Thanks for adding this position!"
      redirect_to position_path(@position)
    else
      flash.now[:error] = "Something went wrong, please try again!"
      render :new
    end
  end

  def edit 
    @position = Position.find(params[:id])
  end

  def update
    @position = Position.find(params[:id])

    if @position.update(position_params)
      redirect_to position_path(@position), notice: "Position was successfully updated!"
    else
      flash.now[:error] = "An error occurred when updating this position"
      render :edit
    end
  end

  def destroy
    @position = Position.find(params[:id])
    @position.destroy

    redirect_to positions_path, notice: "Position was successfully deleted"
  end

  private

  def position_params
   params.require(:position).permit(:name)
 end
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/positions/_form.html.erb
<%= form_for @position do |f| %>

  <% if @position.errors.any? %>
    <% @position.errors.full_messages.each do |message| %>
      <p><%= message %></p>
    <% end %>
  <% end %>

  <p>
    <%= f.label :position_name %><br>
    <%= f.text_field :name %>
  </p>


  <%= f.submit %>
<% end %>

app/views/positions/edit.html.erb
<h1>Edit Position</h1>

<%= link_to "Back to All Positions", position_path %>

<%= render 'form' %>

app/views/positions/index.html.erb
<h1>All Positions</h1>
<h2>
<table>
  <tr>
    <th>Position</th>
  </tr>
  <tbody>
    <% @positions.each do |position| %>
      <tr>
        <td><%= link_to(position.name, position_path(position)) %></td>
        <td>&nbsp 
        </td>
        <td>&nbsp 
        </td>
        <td>&nbsp 
        </td>
        <td>&nbsp 
        </td>
        <td>&nbsp 
        </td>
        <td>&nbsp 
        </td>
        <td>&nbsp 
        </td>
        <td><%= link_to "edit", edit_position_path(position) %></td>
        <td>&nbsp 
        </td>
        <td>&nbsp 
        </td>
        <td><%= link_to "delete", position_path(position), method: :delete, data: {confirm: "Really want to delete this position?"}%></td>
      </tr>
    <% end %>
  </tbody>
</table>
</h2>

<h4><%= link_to "Add a New Position", new_position_path %></h4>

<br />
<br />

app/views/positions/new.html.erb
<h1>Add New Position</h1>


<%= link_to "Back to All Positions", positions_path %>

<%= render 'form' %>

app/views/positions/show.html.erb
<%= link_to "Back to All Positions", positions_path %>

<p>
  <strong>Position:</strong> <%= @position.name %>
</p>

<h3>Players</h3>

<% @players.each do |player| %>
      <tr>
        
        <td><%= image_tag player.photo.url(:small) %></td>
        <strong><td><%= link_to(player.first_name, player_path(player)) %></td>
        <td><%= link_to(player.last_name, player_path(player)) %></td>
        <td>&nbsp 
        </td>
        <td>&nbsp 
        </td>
        <td>&nbsp 
        </td>
        <td><%= link_to(player.team.name, team_path(player.team)) %></td>
        </strong><br><br>
<% end %>

<td><%= link_to "edit", edit_position_path(@position) %></td>