config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :players do
    resources :comments
  end
  resources :authors
  resources :skills
  resources :teams
  resources :leagues
  resources :positions


  
  root "players#index"
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :players
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

   def index
     @authors = Author.all
   end
    
   def show
     @author = Author.find(params[:id])
   end
 
   def new
     @author = Author.new
   end
 
   def create
     @author = Author.new(author_params)
 
     if @author.save
       flash[:notice] = "Author was successfully created"
       redirect_to author_path(@author)
     else
       flash.now[:error] = "An error occurred while saving this author"
       render :new
     end
   end
 
   def edit
     @author = Author.find(params[:id])
   end
 
   def update
    @author = Author.find(params[:id])

    if @author.update(author_params)
      redirect_to author_path(@author), notice: "Author was successfully updated!"
    else
      flash.now[:error] = "An error occurred when updating this Author"
      render :edit
     end
   end
 
   def destroy
     @author = Author.find(params[:id])
     @author.destroy

     redirect_to authors_path, notice: "Author was successfully deleted"
   end
 
   private
 
   def find_author
     @author = Author.find(params[:id])
   end
 
   def author_params
     params.require(:author).permit(:first_name, :last_name)
   end
 end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<%= form_for @author do |f| %>

  <% if @author.errors.any? %>
    <% @author.errors.full_messages.each do |message| %>
      <p><%= message %></p>
    <% end %>
  <% end %>

  <p>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </p>

  <p>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </p>

  <%= f.submit %>
<% end %>

app/views/authors/edit.html.erb
<h1>Add New Author</h1>

<%= link_to "Back to All Authors", authors_path %>

<%= render 'form' %>

app/views/authors/index.html.erb
<h1>The New And Amazing Player Database</h1>

<h1>I am the Author homepage</h1>

<%= link_to "Create a new Author", new_author_path %>

<br />
<br />

<table>
   <tr>
     <th>First Name</th>
     <th>Last Name</th>
     <th>Edit</th>
     <th>Delete</th>
   </tr>
   <tbody>
     <% @authors.each do |author| %>
       <tr>
         <td><%= link_to(author.first_name, author_path(author)) %></td>
         <td><%= author.last_name %></td>
         <td><%= link_to "edit", edit_author_path(author) %></td>
        <td><%= link_to "delete", author_path(author), method: :delete, data: {confirm: "Do you really want to delete this author?"}%></td>
        </tr>
     <% end %>
   </tbody>
 </table> 

app/views/authors/new.html.erb
<h1>Add New Author</h1>

<%= link_to "Back to All Authors", authors_path %>

<%= render 'form' %>

app/views/authors/show.html.erb
<%= link_to "Back to All Authors", authors_path %>

<p>
   <strong>Author First Name:</strong> <%= @author.first_name %>
 </p>
 
 <p>
   <strong>Author Last Name:</strong> <%= @author.last_name %>
 </p>