config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :players do
    resources :comments
  end
  resources :authors
  resources :skills
  resources :teams
  resources :leagues
  resources :positions


  
  root "players#index"
end

app/models/player.rb
class Player < ActiveRecord::Base

  has_attached_file :photo, :styles =>
  { :medium => "300x300>", :thumb => "100x100>", :small =>"100x100>" },
  :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo,
  :content_type => /\Aimage\/.*\Z/

  belongs_to :author
  belongs_to :league
  belongs_to :team
  belongs_to :position
  has_many :player_skills
  has_many :skills, through: :player_skills
  has_many :comments

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :team, presence: true
  validates :position, presence: true



  def self.search(search)
    where("last_name LIKE ?", "%#{search}%")
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :authenticate_user!, except: [ :index, :show ]

  def index
    @players = Player.all

    if params[:search]
      @players = Player.search(params[:search]).order("created_at DESC")
    else
      @players = Player.all.order('created_at ASC')
    end
  end

  def show 
    @player = Player.find(params[:id])
  end

  def new 
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)

    if @player.save
      flash[:notice] = "Thanks for putting this player on the map!"
      redirect_to player_path(@player)
    else
      flash.now[:error] = "Aww... Something went wrong, please try again!"
      render :new
    end
  end

  def edit 
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])

    if @player.update(player_params)
      redirect_to player_path(@player), notice: "Player was successfully updated!"
    else
      flash.now[:error] = "An error occurred when updating this player"
      render :edit
    end
  end

  def destroy
    @player = Player.find(params[:id])
    @player.destroy

    redirect_to players_path, notice: "Player was successfully deleted"
  end

  private

   def player_params
     params.require(:player).permit(:photo, :first_name, :last_name, :height, :weight, :team_id, :number, :bio, :position_id, :author_id, :league_id, skill_ids: [])
  end

end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for @player, :html => { :multipart => true } do |f|  %>

  <% if @player.errors.any? %>
    <% @player.errors.full_messages.each do |message| %>
      <p><%= message %></p>
    <% end %>
  <% end %>

  <p><%= f.file_field :photo %></p>

  <p>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </p>

  <p>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </p>

    <p>
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </p>

   <p>
    <%= f.label :height, "Height in cm" %><br>
    <%= f.text_field :height %>
  </p>

   <p>
    <%= f.label :weight, "Weight in kg" %><br>
    <%= f.text_field :weight %>
  </p>

  <p>
    <%= f.label :position %><br>
    <%= collection_select(:player, :position_id, Position.all, :id, :name, include_blank: true) %>
  </p>

   <p>
    <%= f.label :team %><br>
    <%= collection_select(:player, :team_id, Team.all, :id, :name, include_blank: true) %>
  </p>

  <p>
    <%= f.label :league %><br>
    <%= collection_select(:player, :league_id, League.all, :id, :name, include_blank: true) %>
  </p>

  <p>
    <%= collection_check_boxes(:player, :skill_ids, Skill.all, :id, :name) %>
  </p>

  <p>
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </p>

  <p>
    <%= f.label :author %><br>
    <%= collection_select(:player, :author_id, Author.all, :id, :last_name, include_blank: true) %>
  </p>

  <%= f.submit %>
<% end %>

app/views/players/edit.html.erb
<h1>Edit Player</h1>

<%= link_to "Back to All Players", players_path %>

<%= render 'form' %>

app/views/players/index.html.erb
<body>

    </div>
      <div class="row">
      <div class ="left_buffer">
        <div class="col-md-4">
          <h2>All Players</h2>
          <p>
      <tbody>
        <% @players.each do |player| %>
          <tr>
          
          <td><%= image_tag player.photo.url(:small) %></td>
          <strong><td><%= link_to(player.first_name, player_path(player)) %></td>
          <td><%= link_to(player.last_name, player_path(player)) %></td>
          </strong>
          <em><td><%= player.position.name %></td></em>
          <td><%= link_to "edit", edit_player_path(player) %></td>
          <td><%= link_to "delete", player_path(player), method: :delete, data: {confirm: "Really want to delete this player?"}%></td><br>
        <% end %>

          </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>
        <div class="col-md-4">
          <h2>All Leagues</h2>
            <img src="/images/leagues_map.jpg" alt="All Positions" height="280" width="280" />

          <p><a class="btn btn-default" href="http://localhost:3000/leagues" role="button">View details &raquo;</a></p>
       </div>

        <div class="col-md-4">
          <h2>All Positions</h2>
          <img src="/images/positions.png" alt="All Positions" height="280" width="280" />
          <p><a class="btn btn-default" href="http://localhost:3000/positions" role="button">View details &raquo;</a></p>
        </div>
      </div>

<%= link_to "Create a New Player", new_player_path %>
<%= link_to "Create a New Team", new_team_path %>

app/views/players/new.html.erb
<h1>Add New Player</h1>

<%= link_to "Back to All Players", players_path %>

<%= render 'form' %>

app/views/players/show.html.erb
<%= link_to "Back to All players", players_path %>

<p><%= image_tag @player.photo.url(:medium) %></p>

<p>
  <strong>First Name:</strong> <%= @player.first_name %>
</p>

<p>
  <strong>Last Name:</strong> <%= @player.last_name %>
</p>

<p>
  <strong>Position:</strong> <%= @player.position.name %>
</p>

<p>
  <strong>Team:</strong> <%= @player.team.name %>
</p>

<p>
  <strong>League:</strong><%= @player.league.name %>
</p>

<!-- League comes from external table-->

<p>
  <strong>Height:</strong> <%= @player.height %>
</p>

<p>
  <strong>Weight:</strong> <%= @player.weight %>
</p>

<p>
  <strong>Bio:</strong> <%= @player.bio %>
</p>

<strong>Skills:</strong>
<ul>
  <% @player.skills.each do |skill| %>
  <li><%= skill.name %></li>
  <% end %>
</ul>

<br />
<td><%= link_to "edit", edit_player_path(@player) %></td>

<div id="comments">
  <h2><%= @player.comments.count %> Comments</h2>
  <%= render @player.comments %>
  <h3>Add a comment:</h3>
  <%= render "comments/form"%>
  </div>